### ISSUE TITLE
What do you do?

### ISSUE THREAD

**Issue by vbisbest** [TommyLau/docker-android#1]
Once the image is up and running, how do you build AOSP?  Are there any scripts?
Thanks.

**Comment by TommyLau** [comment]
```
docker run --name="aosp" -v /path/to/aosp:/aosp -ti tommylau/aosp bash
```

This will create a new container, then change directory to `/aosp` in the container, then you can compile the AOSP.

```
cd /aosp
make -j$(nproc)
```

And this is for Android 4.4, if you want to compile Android 7.0, use `docker pull tommylau/aosp:7` instead.

**Comment by vbisbest** [comment]
So we are on our own for pulling down the AOSP repo?  That gets pulled into our host machine under that volume?   Also, I am able to do the "Lunch" command in the container?  I need to build for x86.   Thanks.

**Comment by TommyLau** [comment]
Yes, that's the story, you have to get the repo by yourself.

And then volume it mapping into the container.

`source build/envsetup.sh` might be executed before compile the AOSP.

**NOTICE** Only Android 4.4 with Oracle(Sun) Java 1.6 and Android 7.0 with OpenJDK 1.8 are available right now.
